baseURL = "https://javierarrieroou.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Javier Arriero OÜ"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Javier Arriero OÜ"
author = "Javier Arriero"
description = "Dev teams remote support"
profilePicture = "images/0.jpeg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "LinkedIn"
url = "https://pt.linkedin.com/in/javier-arriero-pais-4668bb128"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/analyticbastard"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:javierarrieropais@outlook.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Privacy"
  weight = 400
  identifier = "privacy"
  url = "/privacy/"
